version: "3"

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: mysql
    command: mysqld --sql_mode="" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: singkatinaja 
  cache:
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    container_name: redis
    restart: always
